# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monfhir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedresourcetype',
            name='collection_name',
            field=models.CharField(default='', help_text='MongoDB Database Name', max_length=256),
        ),
        migrations.AddField(
            model_name='supportedresourcetype',
            name='database_name',
            field=models.CharField(default='', help_text='MongoDB Database Name', max_length=256),
        ),
    ]
