# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monfhir', '0003_auto_20161213_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportedresourcetype',
            old_name='resource_name',
            new_name='resource_type',
        ),
        migrations.AddField(
            model_name='supportedresourcetype',
            name='access_with_no_auth',
            field=models.BooleanField(default=False, help_text='Accessible without auth (for internal use cases)'),
        ),
        migrations.AddField(
            model_name='supportedresourcetype',
            name='access_with_oauth2',
            field=models.BooleanField(default=True, help_text='Accessible via OAuth2'),
        ),
    ]
