# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monfhir', '0004_auto_20161213_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_key', models.CharField(db_index=True, default='', max_length=256)),
                ('key_title', models.SlugField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='supportedresourcetype',
            name='self_only',
            field=models.BooleanField(default=False, help_text='If checked, the me_key will be used instead of supplied id'),
        ),
        migrations.AddField(
            model_name='mekey',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monfhir.SupportedResourceType'),
        ),
        migrations.AddField(
            model_name='mekey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mekey',
            unique_together=set([('user', 'resource_type', 'me_key')]),
        ),
    ]
